[build]
  command = "npm install"
  functions = "netlify/functions"
  publish = "."
  environment = { SECRETS_SCAN_OMIT_KEYS = "FIREBASE_PROJECT_ID,FIREBASE_WEB_API_KEY", SECRETS_SCAN_OMIT_PATHS = "**/node_modules/**" }
